INSERT INTO ADDRESS (STREET, ZIP) VALUES ('Storgaardsvej 23', '4690');
INSERT INTO ADDRESS (STREET, ZIP) VALUES ('Møllevej 18', '4690');
INSERT INTO ADDRESS (STREET, ZIP) VALUES ('Morelhaven 59', '4600');
INSERT INTO ADDRESS (STREET, ZIP) VALUES ('Lidemarksvej 49', '4681');
INSERT INTO ADDRESS (STREET, ZIP) VALUES ('Navervænget 1', '4000');
INSERT INTO ADDRESS (STREET, ZIP) VALUES ('Germinivej 32', '2670');
INSERT INTO ADDRESS (STREET, ZIP) VALUES ('Mortonsvej 21, 2.th.', '2800');
INSERT INTO ADDRESS (STREET, ZIP) VALUES ('Dantes Plads 7', '1556');
INSERT INTO ADDRESS (STREET, ZIP) VALUES ('Sundborvej 19', '5700');
INSERT INTO ADDRESS (STREET, ZIP) VALUES ('Vesterfælledvej 6', '1750');

