DROP TABLE IF EXISTS CITYINFO;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS PHONE;
DROP TABLE IF EXISTS HOBBY;

CREATE TABLE CITYINFO (	
	ZIP INTEGER, 
	CITY VARCHAR(30), 	
	PRIMARY KEY (ZIP)
); 
CREATE TABLE ADDRESS (	
	STREET VARCHAR(30), 
	ZIP INTEGER, 	
	PRIMARY KEY (STREET)
); 
CREATE TABLE PERSON (	
	ID INTEGER, 
	EMAIL VARCHAR(30), 	
    FIRSTNAME VARCHAR(30), 	
    LASTNAME VARCHAR(30), 	
	PRIMARY KEY (ID)
); 
CREATE TABLE PHONE (	
	NUM INTEGER, 
	DESCRIPTION VARCHAR(30), 	
	PRIMARY KEY (NUM)
); 
CREATE TABLE HOBBY (		
	DESCRIPTION VARCHAR(30), 	
	PRIMARY KEY (DESCRIPTION)
); 